package vista;

import controlador.TadLista;
import controlador.tadCola.ColaVacia;
import controlador.tadPila.TadPila;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.vehiculo;

/**
 *
 * @author usuario
 */
public class retiroveh extends javax.swing.JFrame implements Runnable {

    String p, f, h;
    static int posic = 0;
    String dia, mes, annio, horascont;
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    int vh = 0;
    double vmin = 0, vpaga;
    Thread h1;
    int res = 0, resm = 0, consta = 12;
    SimpleDateFormat formatter6 = new SimpleDateFormat("dd/MMM/yyyy HH:mm:ss");

    public retiroveh() {
        initComponents();
        h1 = new Thread(this);
        h1.start();
        setLocationRelativeTo(null);//para centrar la ventana
        setVisible(true);
        Calendar c = Calendar.getInstance();
        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH));
        annio = Integer.toString(c.get(Calendar.YEAR));

        fretiro.setText(dia + "/" + mes + "/" + annio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        placatxt = new javax.swing.JTextField();
        fechaitxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        horaitxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fretiro = new javax.swing.JTextField();
        horasalida = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horasc = new javax.swing.JTextField();
        vpago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jLabel8.setText("Ingreso de vehiculo - Parking Cr");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retiro de vehiculo");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("Parking Cr"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/car.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Placa:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        placatxt.setEditable(false);
        jPanel3.add(placatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, -1));

        fechaitxt.setEditable(false);
        jPanel3.add(fechaitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 230, -1));

        jLabel2.setText("Fecha de ingreso:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Hora de Ingreso:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        horaitxt.setEditable(false);
        jPanel3.add(horaitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 230, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 32, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 560, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel2.setName("Parking Cr"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Fecha de retiro:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setText("Hora de Salida:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel12.setText("Cliente:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        fretiro.setEditable(false);
        jPanel2.add(fretiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 230, -1));

        horasalida.setEditable(false);
        horasalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasalidaActionPerformed(evt);
            }
        });
        jPanel2.add(horasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 230, -1));

        jTextField8.setText("jTextField4");
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 230, -1));

        jLabel7.setText("Nro de horas:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        horasc.setEditable(false);
        horasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horascActionPerformed(evt);
            }
        });
        jPanel2.add(horasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, -1));

        vpago.setEditable(false);
        vpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpagoActionPerformed(evt);
            }
        });
        jPanel2.add(vpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 60, -1));

        jLabel11.setText("Valor a pagar:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        jButton2.setText("eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jButton4.setText("Retirar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 80, -1));

        jButton5.setText("Cancelar");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 560, 200));

        jLabel15.setText("Retiro de vehiculo - Parking Cr");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /**/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        detallesveh de = new detallesveh();
        de.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TadLista lista = new TadLista();
        vehiculo veh;
        lista.mostrarVeh();
        veh = new vehiculo();
        veh.setFechaI(null);
        veh.setPlaca(null);
        veh.setHorasI(null);
        lista.editar(posic, veh);
        lista.mostrarVeh();
        System.out.println("ingreso a la pila");
        TadPila<vehiculo> pila = new TadPila<>();

        pila.apilar(new vehiculo(placatxt.getText(), fechaitxt.getText(), horaitxt.getText(), fretiro.getText(), horasalida.getText(),
                horasc.getText(), vpago.getText()));
        pila.imprimirPila();

        veh = new vehiculo();

        try {
            veh.setPlaca(ingresoveh.cola.primero().getPlaca());
            veh.setFechaI(fretiro.getText());
            veh.setHorasI(horasalida.getText());
            lista.editar(posic, veh);
            try {
                ingresoveh.cola.desencolar();
            } catch (ColaVacia ex) {
                Logger.getLogger(retiroveh.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ColaVacia ex) {
            Logger.getLogger(retiroveh.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpiar();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void horascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horascActionPerformed

    private void horasalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasalidaActionPerformed

    private void vpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vpagoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiroveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiroveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiroveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiroveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new retiroveh();
    }

    public void calculaHoras() {

        if (fechaitxt.getText().length() == 0) {

        } else {
            if (fechaitxt.getText().equals(fretiro.getText())) {
                if (horasalida.getText().substring(9, 11).equals(horaitxt.getText().substring(9, 11))) {

                    if (horasalida.getText().substring(0, 2).equals(horaitxt.getText().substring(0, 2))) {

                        resm = Integer.parseInt(horasalida.getText().substring(3, 5)) - Integer.parseInt(horaitxt.getText().substring(3, 5));
                        res = 0;

                    } else {
                        if (horasalida.getText().substring(3, 5).equals("00")) {
                            resm = 60 - Integer.parseInt(horaitxt.getText().substring(3, 5));
                            res = 0;
                        } else {
                            if (Integer.parseInt(horaitxt.getText().substring(3, 5)) > Integer.parseInt(horasalida.getText().substring(3, 5))) {
                                resm = (60 - Integer.parseInt(horaitxt.getText().substring(3, 5))) + Integer.parseInt(horasalida.getText().substring(3, 5));
                                res = (Integer.parseInt(horasalida.getText().substring(0, 2)) - Integer.parseInt(horaitxt.getText().substring(0, 2))) - 1;
                            } else {
                                resm = Integer.parseInt(horasalida.getText().substring(3, 5)) - Integer.parseInt(horaitxt.getText().substring(3, 5));
                                res = Integer.parseInt(horasalida.getText().substring(0, 2)) - Integer.parseInt(horaitxt.getText().substring(0, 2));
                            }
                        }

                    }

                } else {
                    if (horasalida.getText().substring(0, 2).equals(horaitxt.getText().substring(0, 2))) {

                        resm = Integer.parseInt(horasalida.getText().substring(3, 5)) - Integer.parseInt(horaitxt.getText().substring(3, 5));
                        res = consta + 0;

                    } else {
                        if (horasalida.getText().substring(3, 5).equals("00")) {
                            resm = 60 - Integer.parseInt(horaitxt.getText().substring(3, 5));
                            res = consta + 0;
                        } else {
                            if (Integer.parseInt(horaitxt.getText().substring(3, 5)) > Integer.parseInt(horasalida.getText().substring(3, 5))) {
                                resm = (60 - Integer.parseInt(horaitxt.getText().substring(3, 5))) + Integer.parseInt(horasalida.getText().substring(3, 5));
                                res = (consta + Integer.parseInt(horasalida.getText().substring(0, 2)) - Integer.parseInt(horaitxt.getText().substring(0, 2))) - 1;
                            } else {
                                resm = Integer.parseInt(horasalida.getText().substring(3, 5)) - Integer.parseInt(horaitxt.getText().substring(3, 5));
                                res = consta + Integer.parseInt(horasalida.getText().substring(0, 2)) - Integer.parseInt(horaitxt.getText().substring(0, 2));
                            }
                        }

                    }

                }

            }

        }
    }

    public void calculaVPagar() {
        if (horasc.getText().length() == 4) {
            vh = Integer.parseInt(horasc.getText().substring(0, 1));
            vmin = Integer.parseInt(horasc.getText().substring(2, 4)) * 0.016;
            vpaga = vh + vmin;

        } else {
            if (horasc.getText().length() == 5) {
                vh = Integer.parseInt(horasc.getText().substring(0, 2));
                vmin = Integer.parseInt(horasc.getText().substring(3, 5)) * 0.016;
                vpaga = vh + vmin;
            }
        }

    }

    public void limpiar() {
        placatxt.setText("");
        fechaitxt.setText("");
        horaitxt.setText("");
    }

    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField fechaitxt;
    private javax.swing.JTextField fretiro;
    public static javax.swing.JTextField horaitxt;
    private javax.swing.JTextField horasalida;
    private javax.swing.JTextField horasc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField placatxt;
    private javax.swing.JTextField vpago;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            //(C2 - B2) * 24
            //horasalida.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            horasalida.setText("07:01:00 AM");
            calculaHoras();
            if (resm < 10) {
                horascont = res + ":0" + resm;
            } else {
                horascont = res + ":" + resm;
            }

            horasc.setText(horascont);
            calculaVPagar();
            vpago.setText("$" + Math.round(vpaga * 100.0) / 100.0);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
}
